### ISSUE TITLE
MP同步QQ/网易云歌单插件的反馈。

### ISSUE THREAD

**Issue by baozaodetudou** [baozaodetudou/MoviePilot-Plugins#1]
MP同步QQ/网易云歌单插件的反馈。
插件已经很好用，有效的解决了歌单问题，非常感谢。

因为各大平台歌曲的标题-歌手命名差异等。
能不能：
①标题忽略（）里内容，
②歌手名是多歌手 只要能命中一个，就可以加入歌单。 有两个情况 1是QQ音乐是A/B ，但我存的是A。 2是AQQ音乐是A，但我存的是A/B。
③ 因为都是NAS存的歌，标签都是削刮和自己的习惯保存的，如果歌手G.E.M.邓紫棋 伍佰 & China Blue 我都是改成邓紫棋 伍佰 这样来保存的，这样的有办法匹配吗？ 应该比较难，③可以忽略。。。

冒昧打扰了。 @shuer001

**Comment by baozaodetudou** [comment]
1. 针对①标题忽略（）里内容，已经做了很早之前的版本就做了处理，如果有没处理的建议提供歌单地址
2. 针对多歌手的可以做，但是不会保证准确性
3. 这个和2一样，可以做一些简单的模糊匹配规则，但是可能效果并不理想

**Comment by baozaodetudou** [comment]
需求已经合并

**Comment by shuer001** [comment]
好的，感谢大佬！！！
大佬速度真快！- -
