### ISSUE TITLE
5.7更新后怎么安装都不显示，同猫眼插件安装之类的都正常。。 日志提示都OK  好奇怪。

### ISSUE THREAD

**Issue by shuer001** [baozaodetudou/MoviePilot-Plugins#2]
是不是出新bug了。。5.7更新后怎么安装都不显示，同猫眼插件安装之类的都正常。。 好奇怪。
![QQ截图20240416193740](https://github.com/baozaodetudou/MoviePilot-Plugins/assets/48412081/8d0f9c63-614a-4c4b-93e2-419f8502906d)
![QQ截图20240416195657](https://github.com/baozaodetudou/MoviePilot-Plugins/assets/48412081/ce4693fc-a189-4380-a2f5-b980cc79e88e)
![QQ截图20240416200413](https://github.com/baozaodetudou/MoviePilot-Plugins/assets/48412081/2a1a34d2-cc88-4266-aae1-3c2d04fd9db7)

**Comment by baozaodetudou** [comment]
已解决
